/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AddressResidentialIndicator } from './address-residential-indicator';
// May contain unused imports in some cases
// @ts-ignore
import type { PartialAddress } from './partial-address';

/**
 * @type Address
 * Any residential or business mailing address, anywhere in the world.  > **Note:** Either `name` or `company_name` must be set. Both may be specified, if relevant. 
 * @export
 */
export type Address = PartialAddress;


