/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The error codes that can be returned by the address validation API
 * @export
 * @enum {string}
 */

export const AddressValidationCode = {
    A1000: 'a1000',
    A1001: 'a1001',
    A1002: 'a1002',
    A1003: 'a1003',
    A1004: 'a1004',
    A1005: 'a1005',
    A1006: 'a1006',
    A1007: 'a1007',
    A1008: 'a1008',
    R1000: 'r1000',
    R1001: 'r1001',
    R1002: 'r1002',
    R1003: 'r1003'
} as const;

export type AddressValidationCode = typeof AddressValidationCode[keyof typeof AddressValidationCode];



