/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Contact information for Dangerous goods
 * @export
 * @interface AdvancedShipmentOptionsDangerousGoodsContact
 */
export interface AdvancedShipmentOptionsDangerousGoodsContact {
    /**
     * Name of the contact
     * @type {string}
     * @memberof AdvancedShipmentOptionsDangerousGoodsContact
     */
    'name'?: string;
    /**
     * Phone number of the contact
     * @type {string}
     * @memberof AdvancedShipmentOptionsDangerousGoodsContact
     */
    'phone'?: string;
}

