/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The Windsor framework is a new regulation in the UK that simplifies customs procedures for goods moved from the UK mainland to Northern Ireland.
 * @export
 * @interface AdvancedShipmentOptionsWindsorFrameworkDetails
 */
export interface AdvancedShipmentOptionsWindsorFrameworkDetails {
    /**
     * An indicator that will tell the carrier and HMRC the type of movement for the shipment.
     * @type {string}
     * @memberof AdvancedShipmentOptionsWindsorFrameworkDetails
     */
    'movement_indicator'?: AdvancedShipmentOptionsWindsorFrameworkDetailsMovementIndicatorEnum;
    /**
     * An indicator that allows a shipper to declare the shipment as not-at-risk.
     * @type {boolean}
     * @memberof AdvancedShipmentOptionsWindsorFrameworkDetails
     */
    'not_at_risk'?: boolean;
}

export const AdvancedShipmentOptionsWindsorFrameworkDetailsMovementIndicatorEnum = {
    C2c: 'c2c',
    B2c: 'b2c',
    C2b: 'c2b',
    B2b: 'b2b'
} as const;

export type AdvancedShipmentOptionsWindsorFrameworkDetailsMovementIndicatorEnum = typeof AdvancedShipmentOptionsWindsorFrameworkDetailsMovementIndicatorEnum[keyof typeof AdvancedShipmentOptionsWindsorFrameworkDetailsMovementIndicatorEnum];


