/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Additional information some carriers may provide by which to identify a given label in their system. 
 * @export
 * @interface AlternativeIdentifier
 */
export interface AlternativeIdentifier {
    /**
     * The type of alternative_identifier that corresponds to the value. 
     * @type {string}
     * @memberof AlternativeIdentifier
     */
    'type'?: string;
    /**
     * The value of the alternative_identifier. 
     * @type {string}
     * @memberof AlternativeIdentifier
     */
    'value'?: string;
}

