/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BatchStatus } from './batch-status';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelDownload } from './label-download';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelFormat } from './label-format';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelLayout } from './label-layout';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelError } from './model-error';
// May contain unused imports in some cases
// @ts-ignore
import type { OptionalLink } from './optional-link';
// May contain unused imports in some cases
// @ts-ignore
import type { PaperlessDownload } from './paperless-download';

/**
 * Batches are an advanced feature of ShipStation designed for users who need to generate hundreds or thousands of labels at a time. 
 * @export
 * @interface Batch
 */
export interface Batch {
    /**
     * label layout
     * @type {LabelLayout}
     * @memberof Batch
     */
    'label_layout': LabelLayout;
    /**
     * 
     * @type {LabelFormat}
     * @memberof Batch
     */
    'label_format': LabelFormat;
    /**
     * A string that uniquely identifies the batch
     * @type {string}
     * @memberof Batch
     */
    'batch_id': string;
    /**
     * The batch number.
     * @type {string}
     * @memberof Batch
     */
    'batch_number': string;
    /**
     * A string that uniquely identifies the external batch
     * @type {string}
     * @memberof Batch
     */
    'external_batch_id': string | null;
    /**
     * Custom notes you can add for each created batch
     * @type {string}
     * @memberof Batch
     */
    'batch_notes': string | null;
    /**
     * The date and time the batch was created in ShipStation
     * @type {string}
     * @memberof Batch
     */
    'created_at': string;
    /**
     * The date and time the batch was processed in ShipStation
     * @type {string}
     * @memberof Batch
     */
    'processed_at': string | null;
    /**
     * The number of errors that occurred while generating the batch
     * @type {number}
     * @memberof Batch
     */
    'errors': number;
    /**
     * The errors associated with the failed API call
     * @type {Array<ModelError>}
     * @memberof Batch
     */
    'process_errors': Array<ModelError>;
    /**
     * The number of warnings that occurred while generating the batch
     * @type {number}
     * @memberof Batch
     */
    'warnings': number;
    /**
     * The number of labels generated in the batch
     * @type {number}
     * @memberof Batch
     */
    'completed': number;
    /**
     * The number of forms for customs that are available for download
     * @type {number}
     * @memberof Batch
     */
    'forms': number;
    /**
     * The total of errors, warnings, and completed properties
     * @type {number}
     * @memberof Batch
     */
    'count': number;
    /**
     * The batch shipments endpoint
     * @type {OptionalLink}
     * @memberof Batch
     */
    'batch_shipments_url': OptionalLink;
    /**
     * Link to batch labels query
     * @type {OptionalLink}
     * @memberof Batch
     */
    'batch_labels_url': OptionalLink;
    /**
     * Link to batch errors endpoint
     * @type {OptionalLink}
     * @memberof Batch
     */
    'batch_errors_url': OptionalLink;
    /**
     * The label download for the batch
     * @type {LabelDownload}
     * @memberof Batch
     */
    'label_download': LabelDownload;
    /**
     * The form download for any customs that are needed
     * @type {OptionalLink}
     * @memberof Batch
     */
    'form_download': OptionalLink;
    /**
     * The paperless details which may contain elements like `href`, `instructions` and `handoff_code`.
     * @type {PaperlessDownload}
     * @memberof Batch
     */
    'paperless_download': PaperlessDownload;
    /**
     * 
     * @type {BatchStatus}
     * @memberof Batch
     */
    'status': BatchStatus;
}



