/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A batch response error
 * @export
 * @interface BatchResponseError
 */
export interface BatchResponseError {
    /**
     * Error message associated with the shipment.
     * @type {string}
     * @memberof BatchResponseError
     */
    'error'?: string;
    /**
     * A string that uniquely identifies the shipment
     * @type {string}
     * @memberof BatchResponseError
     */
    'shipment_id'?: string;
    /**
     * An external shipment id associated with the shipment
     * @type {string}
     * @memberof BatchResponseError
     */
    'external_shipment_id'?: string;
}

