/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Advanced options that are specific to the carrier
 * @export
 * @interface CarrierAdvancedOption
 */
export interface CarrierAdvancedOption {
    /**
     * Name of advanced option
     * @type {string}
     * @memberof CarrierAdvancedOption
     */
    'name'?: string;
    /**
     * Default value of option
     * @type {string}
     * @memberof CarrierAdvancedOption
     */
    'default_value'?: string;
    /**
     * Description of option
     * @type {string}
     * @memberof CarrierAdvancedOption
     */
    'description'?: string;
}

