/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Types of payment that are supported
 * @export
 * @enum {string}
 */

export const CollectOnDeliveryPaymentType = {
    Any: 'any',
    Cash: 'cash',
    CashEquivalent: 'cash_equivalent',
    None: 'none'
} as const;

export type CollectOnDeliveryPaymentType = typeof CollectOnDeliveryPaymentType[keyof typeof CollectOnDeliveryPaymentType];



