/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ContactDetails
 */
export interface ContactDetails {
    /**
     * 
     * @type {string}
     * @memberof ContactDetails
     */
    'name': string;
    /**
     * An email address.
     * @type {string}
     * @memberof ContactDetails
     */
    'email': string;
    /**
     * Phone number associated
     * @type {string}
     * @memberof ContactDetails
     */
    'phone': string;
}

