/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Webhook } from './webhook';
// May contain unused imports in some cases
// @ts-ignore
import type { WebhookEvent } from './webhook-event';
// May contain unused imports in some cases
// @ts-ignore
import type { WebhookHeader } from './webhook-header';

/**
 * @type CreateWebhookResponseBody
 * A webhook response body
 * @export
 */
export type CreateWebhookResponseBody = Webhook;


