/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A create batch request body
 * @export
 * @interface CreateBatchRequestBody
 */
export interface CreateBatchRequestBody {
    /**
     * A string that uniquely identifies the external batch
     * @type {string}
     * @memberof CreateBatchRequestBody
     */
    'external_batch_id'?: string;
    /**
     * Add custom messages for a particular batch
     * @type {string}
     * @memberof CreateBatchRequestBody
     */
    'batch_notes'?: string;
    /**
     * Array of shipment IDs used in the batch
     * @type {Array<string>}
     * @memberof CreateBatchRequestBody
     */
    'shipment_ids'?: Array<string>;
    /**
     * Array of rate IDs used in the batch
     * @type {Array<string>}
     * @memberof CreateBatchRequestBody
     */
    'rate_ids'?: Array<string>;
}

