/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateAndProcessBatchRequestBodyProcessLabels } from './create-and-process-batch-request-body-process-labels';

/**
 * A create and process batch request body
 * @export
 * @interface CreateAndProcessBatchRequestBody
 */
export interface CreateAndProcessBatchRequestBody {
    /**
     * A string that uniquely identifies the external batch
     * @type {string}
     * @memberof CreateAndProcessBatchRequestBody
     */
    'external_batch_id'?: string;
    /**
     * Add custom messages for a particular batch
     * @type {string}
     * @memberof CreateAndProcessBatchRequestBody
     */
    'batch_notes'?: string;
    /**
     * Array of shipment IDs used in the batch
     * @type {Array<string>}
     * @memberof CreateAndProcessBatchRequestBody
     */
    'shipment_ids'?: Array<string>;
    /**
     * Array of rate IDs used in the batch
     * @type {Array<string>}
     * @memberof CreateAndProcessBatchRequestBody
     */
    'rate_ids'?: Array<string>;
    /**
     * 
     * @type {CreateAndProcessBatchRequestBodyProcessLabels}
     * @memberof CreateAndProcessBatchRequestBody
     */
    'process_labels'?: CreateAndProcessBatchRequestBodyProcessLabels;
}

