/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WebhookEvent } from './webhook-event';
// May contain unused imports in some cases
// @ts-ignore
import type { WebhookHeader } from './webhook-header';

/**
 * A create webhook request body
 * @export
 * @interface CreateWebhookRequestBody
 */
export interface CreateWebhookRequestBody {
    /**
     * 
     * @type {WebhookEvent}
     * @memberof CreateWebhookRequestBody
     */
    'event': WebhookEvent;
    /**
     * The url that the webhook sends the request to
     * @type {string}
     * @memberof CreateWebhookRequestBody
     */
    'url': string;
    /**
     * Array of custom webhook headers
     * @type {Array<WebhookHeader>}
     * @memberof CreateWebhookRequestBody
     */
    'headers'?: Array<WebhookHeader>;
}



