/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DeprecatedManifest } from './deprecated-manifest';
// May contain unused imports in some cases
// @ts-ignore
import type { ErrorWithLabelId } from './error-with-label-id';
// May contain unused imports in some cases
// @ts-ignore
import type { ErrorWithLabelIdResponseBody } from './error-with-label-id-response-body';
// May contain unused imports in some cases
// @ts-ignore
import type { Manifest } from './manifest';
// May contain unused imports in some cases
// @ts-ignore
import type { ManifestDownload } from './manifest-download';
// May contain unused imports in some cases
// @ts-ignore
import type { ManifestRequestStatus } from './manifest-request-status';
// May contain unused imports in some cases
// @ts-ignore
import type { ManifestRequests } from './manifest-requests';
// May contain unused imports in some cases
// @ts-ignore
import type { Manifests } from './manifests';

/**
 * @type CreateManifestResponseBody
 * A create manifest response body
 * @export
 */
export type CreateManifestResponseBody = DeprecatedManifest & ErrorWithLabelIdResponseBody & ManifestRequests & Manifests;


