/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DisplayScheme } from './display-scheme';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelDownloadType } from './label-download-type';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelFormat } from './label-format';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelLayout } from './label-layout';
// May contain unused imports in some cases
// @ts-ignore
import type { ValidateAddress } from './validate-address';

/**
 * A purchase label without shipment request body
 * @export
 * @interface CreateLabelFromShipmentRequestBody
 */
export interface CreateLabelFromShipmentRequestBody {
    /**
     * 
     * @type {ValidateAddress}
     * @memberof CreateLabelFromShipmentRequestBody
     */
    'validate_address'?: ValidateAddress;
    /**
     * 
     * @type {LabelLayout}
     * @memberof CreateLabelFromShipmentRequestBody
     */
    'label_layout'?: LabelLayout;
    /**
     * 
     * @type {LabelFormat}
     * @memberof CreateLabelFromShipmentRequestBody
     */
    'label_format'?: LabelFormat;
    /**
     * 
     * @type {LabelDownloadType}
     * @memberof CreateLabelFromShipmentRequestBody
     */
    'label_download_type'?: LabelDownloadType;
    /**
     * The display format that the label should be shown in.
     * @type {DisplayScheme}
     * @memberof CreateLabelFromShipmentRequestBody
     */
    'display_scheme'?: DisplayScheme;
}



