/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DisplayScheme } from './display-scheme';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelChargeEvent } from './label-charge-event';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelDownloadType } from './label-download-type';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelFormat } from './label-format';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelLayout } from './label-layout';

/**
 * A create return label request body
 * @export
 * @interface CreateReturnLabelRequestBody
 */
export interface CreateReturnLabelRequestBody {
    /**
     * The label charge event. 
     * @type {LabelChargeEvent}
     * @memberof CreateReturnLabelRequestBody
     */
    'charge_event'?: LabelChargeEvent;
    /**
     * The layout (size) that you want the label to be in.  The `label_format` determines which sizes are allowed.  `4x6` is supported for all label formats, whereas `letter` (8.5\" x 11\") is only supported for `pdf` format. 
     * @type {LabelLayout}
     * @memberof CreateReturnLabelRequestBody
     */
    'label_layout'?: LabelLayout;
    /**
     * The file format that you want the label to be in.  We recommend `pdf` format because it is supported by all carriers, whereas some carriers do not support the `png` or `zpl` formats. 
     * @type {LabelFormat}
     * @memberof CreateReturnLabelRequestBody
     */
    'label_format'?: LabelFormat;
    /**
     * 
     * @type {LabelDownloadType}
     * @memberof CreateReturnLabelRequestBody
     */
    'label_download_type'?: LabelDownloadType;
    /**
     * The display format that the label should be shown in.
     * @type {DisplayScheme}
     * @memberof CreateReturnLabelRequestBody
     */
    'display_scheme'?: DisplayScheme;
    /**
     * The label image resource that was used to create a custom label image.
     * @type {string}
     * @memberof CreateReturnLabelRequestBody
     */
    'label_image_id'?: string | null;
}



