/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * This model represents the amount of the dangerous goods..
 * @export
 * @interface DangerousAmount
 */
export interface DangerousAmount {
    [key: string]: any;

    /**
     * The amount of dangerous goods.
     * @type {number}
     * @memberof DangerousAmount
     */
    'amount'?: number;
    /**
     * The unit of dangerous goods.
     * @type {string}
     * @memberof DangerousAmount
     */
    'unit'?: string | null;
}

