/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The possible delivery confirmation values
 * @export
 * @enum {string}
 */

export const DeliveryConfirmation = {
    None: 'none',
    Delivery: 'delivery',
    Signature: 'signature',
    AdultSignature: 'adult_signature',
    DirectSignature: 'direct_signature',
    DeliveryMailed: 'delivery_mailed',
    VerbalConfirmation: 'verbal_confirmation'
} as const;

export type DeliveryConfirmation = typeof DeliveryConfirmation[keyof typeof DeliveryConfirmation];



