/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DimensionUnit } from './dimension-unit';

/**
 * The dimensions of a package
 * @export
 * @interface Dimensions
 */
export interface Dimensions {
    /**
     * 
     * @type {DimensionUnit}
     * @memberof Dimensions
     */
    'unit': DimensionUnit;
    /**
     * The length of the package, in the specified unit
     * @type {number}
     * @memberof Dimensions
     */
    'length': number;
    /**
     * The width of the package, in the specified unit
     * @type {number}
     * @memberof Dimensions
     */
    'width': number;
    /**
     * The height of the package, in the specified unit
     * @type {number}
     * @memberof Dimensions
     */
    'height': number;
}



