/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The dimension units that are supported by ShipStation .
 * @export
 * @enum {string}
 */

export const DimensionUnit = {
    Inch: 'inch',
    Centimeter: 'centimeter'
} as const;

export type DimensionUnit = typeof DimensionUnit[keyof typeof DimensionUnit];



