/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetInventoryLevels200ResponseLinks } from './get-inventory-levels200-response-links';
// May contain unused imports in some cases
// @ts-ignore
import type { GetInventoryWarehouses200ResponseInventoryWarehousesInner } from './get-inventory-warehouses200-response-inventory-warehouses-inner';

/**
 * 
 * @export
 * @interface GetInventoryWarehouses200Response
 */
export interface GetInventoryWarehouses200Response {
    /**
     * 
     * @type {Array<GetInventoryWarehouses200ResponseInventoryWarehousesInner>}
     * @memberof GetInventoryWarehouses200Response
     */
    'inventory_warehouses'?: Array<GetInventoryWarehouses200ResponseInventoryWarehousesInner>;
    /**
     * 
     * @type {number}
     * @memberof GetInventoryWarehouses200Response
     */
    'total'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetInventoryWarehouses200Response
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetInventoryWarehouses200Response
     */
    'pages'?: number;
    /**
     * 
     * @type {GetInventoryLevels200ResponseLinks}
     * @memberof GetInventoryWarehouses200Response
     */
    'links'?: GetInventoryLevels200ResponseLinks;
}

