/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetInventoryLevels200ResponseInventoryInnerAverageCost } from './get-inventory-levels200-response-inventory-inner-average-cost';

/**
 * 
 * @export
 * @interface GetInventoryLevels200ResponseInventoryInner
 */
export interface GetInventoryLevels200ResponseInventoryInner {
    /**
     * 
     * @type {string}
     * @memberof GetInventoryLevels200ResponseInventoryInner
     */
    'sku'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetInventoryLevels200ResponseInventoryInner
     */
    'on_hand'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetInventoryLevels200ResponseInventoryInner
     */
    'allocated'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetInventoryLevels200ResponseInventoryInner
     */
    'available'?: number;
    /**
     * 
     * @type {GetInventoryLevels200ResponseInventoryInnerAverageCost}
     * @memberof GetInventoryLevels200ResponseInventoryInner
     */
    'average_cost'?: GetInventoryLevels200ResponseInventoryInnerAverageCost;
    /**
     * 
     * @type {string}
     * @memberof GetInventoryLevels200ResponseInventoryInner
     */
    'inventory_warehouse_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetInventoryLevels200ResponseInventoryInner
     */
    'inventory_location_id'?: string;
}

