/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetInventoryLevels200ResponseInventoryInner } from './get-inventory-levels200-response-inventory-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { GetInventoryLevels200ResponseLinks } from './get-inventory-levels200-response-links';

/**
 * 
 * @export
 * @interface GetInventoryLevels200Response
 */
export interface GetInventoryLevels200Response {
    /**
     * 
     * @type {Array<GetInventoryLevels200ResponseInventoryInner>}
     * @memberof GetInventoryLevels200Response
     */
    'inventory'?: Array<GetInventoryLevels200ResponseInventoryInner>;
    /**
     * 
     * @type {number}
     * @memberof GetInventoryLevels200Response
     */
    'total'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetInventoryLevels200Response
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetInventoryLevels200Response
     */
    'pages'?: number;
    /**
     * 
     * @type {GetInventoryLevels200ResponseLinks}
     * @memberof GetInventoryLevels200Response
     */
    'links'?: GetInventoryLevels200ResponseLinks;
}

