/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetInventoryLevels200ResponseLinksFirst } from './get-inventory-levels200-response-links-first';

/**
 * 
 * @export
 * @interface GetInventoryLevels200ResponseLinks
 */
export interface GetInventoryLevels200ResponseLinks {
    /**
     * 
     * @type {GetInventoryLevels200ResponseLinksFirst}
     * @memberof GetInventoryLevels200ResponseLinks
     */
    'first'?: GetInventoryLevels200ResponseLinksFirst;
    /**
     * 
     * @type {GetInventoryLevels200ResponseLinksFirst}
     * @memberof GetInventoryLevels200ResponseLinks
     */
    'last'?: GetInventoryLevels200ResponseLinksFirst;
    /**
     * 
     * @type {GetInventoryLevels200ResponseLinksFirst}
     * @memberof GetInventoryLevels200ResponseLinks
     */
    'prev'?: GetInventoryLevels200ResponseLinksFirst;
    /**
     * 
     * @type {GetInventoryLevels200ResponseLinksFirst}
     * @memberof GetInventoryLevels200ResponseLinks
     */
    'next'?: GetInventoryLevels200ResponseLinksFirst;
}

