/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AlternativeIdentifier } from './alternative-identifier';
// May contain unused imports in some cases
// @ts-ignore
import type { DisplayScheme } from './display-scheme';
// May contain unused imports in some cases
// @ts-ignore
import type { Label } from './label';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelChargeEvent } from './label-charge-event';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelDownload } from './label-download';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelDownloadType } from './label-download-type';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelFormat } from './label-format';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelLayout } from './label-layout';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelPackagesInner } from './label-packages-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelStatus } from './label-status';
// May contain unused imports in some cases
// @ts-ignore
import type { Link } from './link';
// May contain unused imports in some cases
// @ts-ignore
import type { MonetaryValue } from './monetary-value';
// May contain unused imports in some cases
// @ts-ignore
import type { PaperlessDownload } from './paperless-download';
// May contain unused imports in some cases
// @ts-ignore
import type { Shipment } from './shipment';
// May contain unused imports in some cases
// @ts-ignore
import type { TrackingStatus } from './tracking-status';
// May contain unused imports in some cases
// @ts-ignore
import type { ValidateAddress } from './validate-address';

/**
 * @type GetLabelByIdResponseBody
 * A get label by id response body
 * @export
 */
export type GetLabelByIdResponseBody = Label;


