/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomsItem } from './customs-item';
// May contain unused imports in some cases
// @ts-ignore
import type { ImporterOfRecords } from './importer-of-records';
// May contain unused imports in some cases
// @ts-ignore
import type { InvoiceAdditionalDetails } from './invoice-additional-details';
// May contain unused imports in some cases
// @ts-ignore
import type { NonDelivery } from './non-delivery';
// May contain unused imports in some cases
// @ts-ignore
import type { PackageContents } from './package-contents';
// May contain unused imports in some cases
// @ts-ignore
import type { TermsOfTradeCode } from './terms-of-trade-code';

/**
 * Options for international shipments, such as customs declarations.
 * @export
 * @interface InternationalShipmentOptions
 */
export interface InternationalShipmentOptions {
    [key: string]: any;

    /**
     * The type of contents in this shipment.  This may impact import duties or customs treatment.
     * @type {PackageContents}
     * @memberof InternationalShipmentOptions
     */
    'contents': PackageContents;
    /**
     * Explanation for contents (required if the `contents` is provided as `other`)
     * @type {string}
     * @memberof InternationalShipmentOptions
     */
    'contents_explanation'?: string;
    /**
     * Indicates what to do if a package is unable to be delivered.
     * @type {NonDelivery}
     * @memberof InternationalShipmentOptions
     */
    'non_delivery': NonDelivery;
    /**
     * Specifies the supported terms of trade code (incoterms)
     * @type {TermsOfTradeCode}
     * @memberof InternationalShipmentOptions
     */
    'terms_of_trade_code'?: TermsOfTradeCode;
    /**
     * Declaration statement to be placed on the commercial invoice
     * @type {string}
     * @memberof InternationalShipmentOptions
     */
    'declaration'?: string;
    /**
     * 
     * @type {InvoiceAdditionalDetails}
     * @memberof InternationalShipmentOptions
     */
    'invoice_additional_details'?: InvoiceAdditionalDetails;
    /**
     * 
     * @type {ImporterOfRecords}
     * @memberof InternationalShipmentOptions
     */
    'importer_of_record'?: ImporterOfRecords;
    /**
     * Customs declarations for each item in the shipment. (Please provide this information under `products` inside `packages`)
     * @type {Array<CustomsItem>}
     * @memberof InternationalShipmentOptions
     * @deprecated
     */
    'customs_items'?: Array<CustomsItem>;
}



