/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EstimatedImportCharges } from './estimated-import-charges';
// May contain unused imports in some cases
// @ts-ignore
import type { MonetaryValue } from './monetary-value';

/**
 * The additional information to put on commercial invoice 
 * @export
 * @interface InvoiceAdditionalDetails
 */
export interface InvoiceAdditionalDetails {
    /**
     * Freight Charge for shipment.
     * @type {MonetaryValue}
     * @memberof InvoiceAdditionalDetails
     */
    'freight_charge'?: MonetaryValue;
    /**
     * Insurance Charge for shipment.
     * @type {MonetaryValue}
     * @memberof InvoiceAdditionalDetails
     */
    'insurance_charge'?: MonetaryValue;
    /**
     * Discount for shipment.
     * @type {MonetaryValue}
     * @memberof InvoiceAdditionalDetails
     */
    'discount'?: MonetaryValue;
    /**
     * Estimated import charges for commercial invoices for international shipments.
     * @type {EstimatedImportCharges}
     * @memberof InvoiceAdditionalDetails
     */
    'estimated_import_charges'?: EstimatedImportCharges;
    /**
     * Other charge for shipment.
     * @type {MonetaryValue}
     * @memberof InvoiceAdditionalDetails
     */
    'other_charge'?: MonetaryValue;
    /**
     * Description for the other charge (if provided).
     * @type {string}
     * @memberof InvoiceAdditionalDetails
     */
    'other_charge_description'?: string;
}

