/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AlternativeIdentifier } from './alternative-identifier';
// May contain unused imports in some cases
// @ts-ignore
import type { Dimensions } from './dimensions';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelDownload } from './label-download';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelMessages } from './label-messages';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelPackage } from './label-package';
// May contain unused imports in some cases
// @ts-ignore
import type { MonetaryValue } from './monetary-value';
// May contain unused imports in some cases
// @ts-ignore
import type { OptionalLink } from './optional-link';
// May contain unused imports in some cases
// @ts-ignore
import type { PaperlessDownload } from './paperless-download';
// May contain unused imports in some cases
// @ts-ignore
import type { Weight } from './weight';

/**
 * @type LabelPackagesInner
 * @export
 */
export type LabelPackagesInner = LabelPackage;


