/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Custom messages to print on the shipping label for the package.  These are typically used to print invoice numbers, product numbers, or other internal reference numbers.  Not all carriers support label messages. The number of lines and the maximum length of each line also varies by carrier.  |Carrier            |Max lines |Max line length |-------------------|----------|-------------------- |USPS (Stamps.com)  |3         |60 |FedEx              |3         |35 for the first line. 30 for additional lines. |UPS                |2         |35 |OnTrac             |2         |25 
 * @export
 * @interface LabelMessages
 */
export interface LabelMessages {
    [key: string]: any;

    /**
     * The first line of the custom label message.  Some carriers may prefix this line with something like \"REF\", \"Reference\", \"Trx Ref No.\", etc. 
     * @type {string}
     * @memberof LabelMessages
     */
    'reference1': string | null;
    /**
     * The second line of the custom label message.  Some carriers may prefix this line with something like \"INV\", \"Reference 2\", \"Trx Ref No.\", etc. 
     * @type {string}
     * @memberof LabelMessages
     */
    'reference2': string | null;
    /**
     * The third line of the custom label message.  Some carriers may prefix this line with something like \"PO\", \"Reference 3\", etc. 
     * @type {string}
     * @memberof LabelMessages
     */
    'reference3': string | null;
}

