/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The possible statuses that a [shipping label] can be in.  |Status       |Description |:------------|:----------------------------------------------------- |`processing` |When labels are created in a [batch], it may take a few minutes for all of the labels in the batch to be created.  During this period, they will be in `processing` status. |`completed`  |The label was successfully created |`error`      |The label could not be created due to an error, such as an invalid delivery address |`voided`     |The label has been [voided] 
 * @export
 * @enum {string}
 */

export const LabelStatus = {
    Processing: 'processing',
    Completed: 'completed',
    Error: 'error',
    Voided: 'voided'
} as const;

export type LabelStatus = typeof LabelStatus[keyof typeof LabelStatus];



