/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Determines when the user\'s account will be charged for the label.
 * @export
 * @enum {string}
 */

export const LabelChargeEvent = {
    CarrierDefault: 'carrier_default',
    OnCreation: 'on_creation',
    OnCarrierAcceptance: 'on_carrier_acceptance'
} as const;

export type LabelChargeEvent = typeof LabelChargeEvent[keyof typeof LabelChargeEvent];



