/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The possible normalized reasons a label void request may not have been approved
 * @export
 * @enum {string}
 */

export const LabelVoidFailureReason = {
    Unknown: 'unknown',
    Unspecified: 'unspecified',
    ValidationFailed: 'validation_failed',
    LabelNotFoundWithinVoidPeriod: 'label_not_found_within_void_period',
    LabelAlreadyUsed: 'label_already_used',
    LabelAlreadyVoided: 'label_already_voided',
    ContactCarrier: 'contact_carrier'
} as const;

export type LabelVoidFailureReason = typeof LabelVoidFailureReason[keyof typeof LabelVoidFailureReason];



