/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PaginationLink } from './pagination-link';
// May contain unused imports in some cases
// @ts-ignore
import type { Pickup } from './pickup';

/**
 * A list pickup response body
 * @export
 * @interface ListPickupResponseBody
 */
export interface ListPickupResponseBody {
    /**
     * An array of pickups associated with the user\'s account.
     * @type {Array<Pickup>}
     * @memberof ListPickupResponseBody
     */
    'pickups': Array<Pickup>;
    /**
     * The total number of pickups returned
     * @type {number}
     * @memberof ListPickupResponseBody
     */
    'total': number;
    /**
     * Current page of the list pickups results
     * @type {number}
     * @memberof ListPickupResponseBody
     */
    'page': number;
    /**
     * Total number of pages for list pickups results
     * @type {number}
     * @memberof ListPickupResponseBody
     */
    'pages': number;
    /**
     * Helpful links to other pages of results
     * @type {PaginationLink}
     * @memberof ListPickupResponseBody
     */
    'links': PaginationLink;
}

