/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Manifest } from './manifest';
// May contain unused imports in some cases
// @ts-ignore
import type { PaginationLink } from './pagination-link';

/**
 * A list manifests response body
 * @export
 * @interface ListManifestsResponseBody
 */
export interface ListManifestsResponseBody {
    /**
     * The list of available manifests
     * @type {Array<Manifest>}
     * @memberof ListManifestsResponseBody
     */
    'manifests': Array<Manifest>;
    /**
     * The total number of manifests returned
     * @type {number}
     * @memberof ListManifestsResponseBody
     */
    'total': number;
    /**
     * Current page of the list manifests results
     * @type {number}
     * @memberof ListManifestsResponseBody
     */
    'page': number;
    /**
     * Total number of pages for list manifests results
     * @type {number}
     * @memberof ListManifestsResponseBody
     */
    'pages': number;
    /**
     * Helpful links to other pages of results
     * @type {PaginationLink}
     * @memberof ListManifestsResponseBody
     */
    'links': PaginationLink;
}

