/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Tag } from './tag';

/**
 * Response body from a successful GET /tags API call
 * @export
 * @interface ListTagsResponseBody
 */
export interface ListTagsResponseBody {
    /**
     * The array of tags returned by the API call
     * @type {Array<Tag>}
     * @memberof ListTagsResponseBody
     */
    'tags'?: Array<Tag>;
}

