/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetInventoryLevels200ResponseLinks } from './get-inventory-levels200-response-links';
// May contain unused imports in some cases
// @ts-ignore
import type { ListInventoryLocations200ResponseInventoryLocationsInner } from './list-inventory-locations200-response-inventory-locations-inner';

/**
 * 
 * @export
 * @interface ListInventoryLocations200Response
 */
export interface ListInventoryLocations200Response {
    /**
     * 
     * @type {Array<ListInventoryLocations200ResponseInventoryLocationsInner>}
     * @memberof ListInventoryLocations200Response
     */
    'inventory_locations'?: Array<ListInventoryLocations200ResponseInventoryLocationsInner>;
    /**
     * 
     * @type {number}
     * @memberof ListInventoryLocations200Response
     */
    'total'?: number;
    /**
     * 
     * @type {number}
     * @memberof ListInventoryLocations200Response
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof ListInventoryLocations200Response
     */
    'pages'?: number;
    /**
     * 
     * @type {GetInventoryLevels200ResponseLinks}
     * @memberof ListInventoryLocations200Response
     */
    'links'?: GetInventoryLevels200ResponseLinks;
}

