/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Label } from './label';
// May contain unused imports in some cases
// @ts-ignore
import type { PagedListResponseBody } from './paged-list-response-body';
// May contain unused imports in some cases
// @ts-ignore
import type { PaginationLink } from './pagination-link';

/**
 * @type ListLabelsResponseBody
 * A list label response body
 * @export
 */
export type ListLabelsResponseBody = PagedListResponseBody;


