/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelError } from './model-error';
// May contain unused imports in some cases
// @ts-ignore
import type { Rate } from './rate';
// May contain unused imports in some cases
// @ts-ignore
import type { RateResponseStatus } from './rate-response-status';
// May contain unused imports in some cases
// @ts-ignore
import type { RatesInformation } from './rates-information';

/**
 * @type ListShipmentRatesResponseBody
 * A list shipment rates response body
 * @export
 */
export type ListShipmentRatesResponseBody = RatesInformation;


