/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ListInventoryLocations200ResponseInventoryLocationsInner
 */
export interface ListInventoryLocations200ResponseInventoryLocationsInner {
    /**
     * 
     * @type {string}
     * @memberof ListInventoryLocations200ResponseInventoryLocationsInner
     */
    'inventory_location_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ListInventoryLocations200ResponseInventoryLocationsInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ListInventoryLocations200ResponseInventoryLocationsInner
     */
    'inventory_warehouse_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ListInventoryLocations200ResponseInventoryLocationsInner
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ListInventoryLocations200ResponseInventoryLocationsInner
     */
    'updated_at'?: string;
}

