/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ManifestRequestStatus } from './manifest-request-status';

/**
 * A reference to the manifest request
 * @export
 * @interface ManifestRequests
 */
export interface ManifestRequests {
    /**
     * A string that uniquely identifies a manifest request
     * @type {string}
     * @memberof ManifestRequests
     */
    'manifest_request_id'?: string;
    /**
     * 
     * @type {ManifestRequestStatus}
     * @memberof ManifestRequests
     */
    'status'?: ManifestRequestStatus;
}



