/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ManifestDownload } from './manifest-download';

/**
 * Used for combining packages into one scannable form that a carrier can use when picking up a large  number of shipments 
 * @export
 * @interface Manifest
 */
export interface Manifest {
    /**
     * A string that uniquely identifies the manifest
     * @type {string}
     * @memberof Manifest
     */
    'manifest_id'?: string;
    /**
     * A string that uniquely identifies the form
     * @type {string}
     * @memberof Manifest
     */
    'form_id'?: string;
    /**
     * The date-time that the manifest was created
     * @type {string}
     * @memberof Manifest
     */
    'created_at'?: string;
    /**
     * The date-time that the manifests shipments will be picked up
     * @type {string}
     * @memberof Manifest
     */
    'ship_date'?: string;
    /**
     * The number of shipments that are included in this manifest
     * @type {number}
     * @memberof Manifest
     */
    'shipments'?: number;
    /**
     * An array of the label ids used in this manifest.
     * @type {Array<string>}
     * @memberof Manifest
     */
    'label_ids'?: Array<string>;
    /**
     * A string that uniquely identifies the warehouse
     * @type {string}
     * @memberof Manifest
     */
    'warehouse_id'?: string;
    /**
     * A string that uniquely identifies the submission
     * @type {string}
     * @memberof Manifest
     */
    'submission_id'?: string;
    /**
     * A string that uniquely identifies the carrier
     * @type {string}
     * @memberof Manifest
     */
    'carrier_id'?: string;
    /**
     * 
     * @type {ManifestDownload}
     * @memberof Manifest
     */
    'manifest_download'?: ManifestDownload;
}

