/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ErrorCode } from './error-code';
// May contain unused imports in some cases
// @ts-ignore
import type { ErrorSource } from './error-source';
// May contain unused imports in some cases
// @ts-ignore
import type { ErrorType } from './error-type';

/**
 * The error structure that gets returned with almost all failed API calls 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 
     * @type {ErrorSource}
     * @memberof ModelError
     */
    'error_source': ErrorSource;
    /**
     * 
     * @type {ErrorType}
     * @memberof ModelError
     */
    'error_type': ErrorType;
    /**
     * 
     * @type {ErrorCode}
     * @memberof ModelError
     */
    'error_code': ErrorCode;
    /**
     * An error message associated with the failed API call
     * @type {string}
     * @memberof ModelError
     */
    'message': string;
}



