/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A modify batch object
 * @export
 * @interface ModifyBatch
 */
export interface ModifyBatch {
    /**
     * The Shipment Ids to be modified on the batch
     * @type {Array<string>}
     * @memberof ModifyBatch
     */
    'shipment_ids'?: Array<string>;
    /**
     * Array of Rate IDs to be modifed on the batch
     * @type {Array<string>}
     * @memberof ModifyBatch
     */
    'rate_ids'?: Array<string>;
}

