/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A monetary value, such as the price of a shipping label, the insured value of a package, or an account balance. 
 * @export
 * @interface MonetaryValue
 */
export interface MonetaryValue {
    /**
     * The currencies that are supported by ShipStation are the ones that specified by ISO 4217: https://www.iso.org/iso-4217-currency-codes.html 
     * @type {string}
     * @memberof MonetaryValue
     */
    'currency': string;
    /**
     * The monetary amount, in the specified currency.
     * @type {number}
     * @memberof MonetaryValue
     */
    'amount': number;
}

