/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A link to a related resource, or an empty object if there is no resource to link to
 * @export
 * @interface OptionalLink
 */
export interface OptionalLink {
    /**
     * The URL of the linked resource, if any
     * @type {string}
     * @memberof OptionalLink
     */
    'href'?: string;
    /**
     * The type of resource, or the type of relationship to the parent resource
     * @type {string}
     * @memberof OptionalLink
     */
    'type'?: string;
}

