/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Indicates if the package will be picked up or dropped off by the carrier
 * @export
 * @enum {string}
 */

export const OriginType = {
    Pickup: 'pickup',
    DropOff: 'drop_off'
} as const;

export type OriginType = typeof OriginType[keyof typeof OriginType];



