/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The possible package contents values
 * @export
 * @enum {string}
 */

export const PackageContents = {
    Merchandise: 'merchandise',
    Documents: 'documents',
    Gift: 'gift',
    ReturnedGoods: 'returned_goods',
    Sample: 'sample',
    Other: 'other'
} as const;

export type PackageContents = typeof PackageContents[keyof typeof PackageContents];



