/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Dimensions } from './dimensions';

/**
 * A package type that a carrier supports for shipment.
 * @export
 * @interface PackageType
 */
export interface PackageType {
    /**
     * A string that uniquely identifies the package.
     * @type {string}
     * @memberof PackageType
     */
    'package_id'?: string;
    /**
     * A [package type] , such as `thick_envelope`, `small_flat_rate_box`, `large_package`, etc.  Use the code `package` for custom or unknown package types. 
     * @type {string}
     * @memberof PackageType
     */
    'package_code': string;
    /**
     * 
     * @type {string}
     * @memberof PackageType
     */
    'name': string;
    /**
     * The custom dimensions for the package.
     * @type {Dimensions}
     * @memberof PackageType
     */
    'dimensions'?: Dimensions;
    /**
     * Provides a helpful description for the custom package.
     * @type {string}
     * @memberof PackageType
     */
    'description'?: string | null;
}

