/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AddressResidentialIndicator } from './address-residential-indicator';

/**
 * A complete or partial mailing address.
 * @export
 * @interface PartialAddress
 */
export interface PartialAddress {
    /**
     * The name of a contact person at this address.  This field may be set instead of - or in addition to - the `company_name` field. 
     * @type {string}
     * @memberof PartialAddress
     */
    'name'?: string;
    /**
     * The phone number of a contact person at this address.  The format of this phone number varies depending on the country. 
     * @type {string}
     * @memberof PartialAddress
     */
    'phone'?: string;
    /**
     * Email for the address owner. 
     * @type {string}
     * @memberof PartialAddress
     */
    'email'?: string | null;
    /**
     * If this is a business address, then the company name should be specified here. 
     * @type {string}
     * @memberof PartialAddress
     */
    'company_name'?: string | null;
    /**
     * The first line of the street address.  For some addresses, this may be the only line.  Other addresses may require 2 or 3 lines. 
     * @type {string}
     * @memberof PartialAddress
     */
    'address_line1'?: string;
    /**
     * The second line of the street address.  For some addresses, this line may not be needed. 
     * @type {string}
     * @memberof PartialAddress
     */
    'address_line2'?: string | null;
    /**
     * The third line of the street address.  For some addresses, this line may not be needed. 
     * @type {string}
     * @memberof PartialAddress
     */
    'address_line3'?: string | null;
    /**
     * The name of the city or locality
     * @type {string}
     * @memberof PartialAddress
     */
    'city_locality'?: string;
    /**
     * The state or province.  For some countries (including the U.S.) only abbreviations are allowed.  Other countries allow the full name or abbreviation. 
     * @type {string}
     * @memberof PartialAddress
     */
    'state_province'?: string;
    /**
     * postal code
     * @type {string}
     * @memberof PartialAddress
     */
    'postal_code'?: string;
    /**
     * The two-letter [ISO 3166-1 country code](https://en.wikipedia.org/wiki/ISO_3166-1) 
     * @type {string}
     * @memberof PartialAddress
     */
    'country_code'?: string;
    /**
     * Indicates whether this is a residential address.
     * @type {AddressResidentialIndicator}
     * @memberof PartialAddress
     */
    'address_residential_indicator'?: AddressResidentialIndicator;
}



