/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaymentAmount
 */
export interface PaymentAmount {
    /**
     * The currencies that are supported by ShipStation are the ones that specified by ISO 4217: https://www.iso.org/iso-4217-currency-codes.html 
     * @type {string}
     * @memberof PaymentAmount
     */
    'currency'?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentAmount
     */
    'amount'?: number;
}

