/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Address } from './address';
// May contain unused imports in some cases
// @ts-ignore
import type { ContactDetails } from './contact-details';
// May contain unused imports in some cases
// @ts-ignore
import type { PickupPickupWindowsInner } from './pickup-pickup-windows-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { PickupWindow } from './pickup-window';

/**
 * The information necessary to schedule a package pickup 
 * @export
 * @interface Pickup
 */
export interface Pickup {
    /**
     * Pickup Resource ID
     * @type {string}
     * @memberof Pickup
     */
    'pickup_id'?: string;
    /**
     * Label IDs that will be included in the pickup request
     * @type {Array<string>}
     * @memberof Pickup
     */
    'label_ids'?: Array<string>;
    /**
     * The date and time that the pickup was created in ShipStation .
     * @type {string}
     * @memberof Pickup
     */
    'created_at'?: string;
    /**
     * The date and time that the pickup was cancelled in ShipStation .
     * @type {string}
     * @memberof Pickup
     */
    'cancelled_at'?: string;
    /**
     * The carrier_id associated with the pickup
     * @type {string}
     * @memberof Pickup
     */
    'carrier_id'?: string;
    /**
     * The carrier confirmation number for the scheduled pickup.
     * @type {string}
     * @memberof Pickup
     */
    'confirmation_number'?: string | null;
    /**
     * The warehouse_id associated with the pickup
     * @type {string}
     * @memberof Pickup
     */
    'warehouse_id'?: string;
    /**
     * 
     * @type {Address}
     * @memberof Pickup
     */
    'pickup_address'?: Address;
    /**
     * 
     * @type {ContactDetails}
     * @memberof Pickup
     */
    'contact_details'?: ContactDetails;
    /**
     * Used by some carriers to give special instructions for a package pickup
     * @type {string}
     * @memberof Pickup
     */
    'pickup_notes'?: string;
    /**
     * 
     * @type {PickupWindow}
     * @memberof Pickup
     */
    'pickup_window'?: PickupWindow;
    /**
     * An array of available pickup windows. Carriers can return multiple times that they will pickup packages. 
     * @type {Array<PickupPickupWindowsInner>}
     * @memberof Pickup
     */
    'pickup_windows'?: Array<PickupPickupWindowsInner>;
}

