/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DisplayScheme } from './display-scheme';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelFormat } from './label-format';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelLayout } from './label-layout';

/**
 * A process batch request body
 * @export
 * @interface ProcessBatchRequestBody
 */
export interface ProcessBatchRequestBody {
    /**
     * The Ship date the batch is being processed for
     * @type {string}
     * @memberof ProcessBatchRequestBody
     */
    'ship_date'?: string;
    /**
     * 
     * @type {LabelLayout}
     * @memberof ProcessBatchRequestBody
     */
    'label_layout'?: LabelLayout;
    /**
     * 
     * @type {LabelFormat}
     * @memberof ProcessBatchRequestBody
     */
    'label_format'?: LabelFormat;
    /**
     * The display format that the label should be shown in.
     * @type {DisplayScheme}
     * @memberof ProcessBatchRequestBody
     */
    'display_scheme'?: DisplayScheme;
}



