/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RateEstimateByCarrierIds
 */
export interface RateEstimateByCarrierIds {
    /**
     * Array of Carrier Ids
     * @type {Array<string>}
     * @memberof RateEstimateByCarrierIds
     */
    'carrier_ids'?: Array<string>;
}

