/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelError } from './model-error';
// May contain unused imports in some cases
// @ts-ignore
import type { Rate } from './rate';
// May contain unused imports in some cases
// @ts-ignore
import type { RateResponseStatus } from './rate-response-status';

/**
 * A rates information resource
 * @export
 * @interface RatesInformation
 */
export interface RatesInformation {
    /**
     * An array of shipment rates
     * @type {Array<Rate>}
     * @memberof RatesInformation
     */
    'rates'?: Array<Rate>;
    /**
     * An array of invalid shipment rates
     * @type {Array<Rate>}
     * @memberof RatesInformation
     */
    'invalid_rates'?: Array<Rate>;
    /**
     * A string that uniquely identifies the rate request
     * @type {string}
     * @memberof RatesInformation
     */
    'rate_request_id'?: string;
    /**
     * A string that uniquely identifies the shipment
     * @type {string}
     * @memberof RatesInformation
     */
    'shipment_id'?: string;
    /**
     * When the rate was created
     * @type {string}
     * @memberof RatesInformation
     */
    'created_at'?: string;
    /**
     * 
     * @type {RateResponseStatus}
     * @memberof RatesInformation
     */
    'status'?: RateResponseStatus;
    /**
     * 
     * @type {Array<ModelError>}
     * @memberof RatesInformation
     */
    'errors'?: Array<ModelError>;
}



