/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AddressValidationCode } from './address-validation-code';
// May contain unused imports in some cases
// @ts-ignore
import type { AddressValidationDetailCode } from './address-validation-detail-code';
// May contain unused imports in some cases
// @ts-ignore
import type { AddressValidationMessageType } from './address-validation-message-type';

/**
 * A response message that displays when additional info is needed for an address validation request.
 * @export
 * @interface ResponseMessage
 */
export interface ResponseMessage {
    [key: string]: any;

    /**
     * 
     * @type {AddressValidationCode}
     * @memberof ResponseMessage
     */
    'code': AddressValidationCode;
    /**
     * Message explaining the address validation error
     * @type {string}
     * @memberof ResponseMessage
     */
    'message': string;
    /**
     * 
     * @type {AddressValidationMessageType}
     * @memberof ResponseMessage
     */
    'type': AddressValidationMessageType;
    /**
     * 
     * @type {AddressValidationDetailCode}
     * @memberof ResponseMessage
     */
    'detail_code': AddressValidationDetailCode | null;
}



