/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AdvancedShipmentOptions } from './advanced-shipment-options';
// May contain unused imports in some cases
// @ts-ignore
import type { DeliveryConfirmation } from './delivery-confirmation';
// May contain unused imports in some cases
// @ts-ignore
import type { InsuranceProvider } from './insurance-provider';
// May contain unused imports in some cases
// @ts-ignore
import type { InternationalShipmentOptions } from './international-shipment-options';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderSourceName } from './order-source-name';
// May contain unused imports in some cases
// @ts-ignore
import type { Package } from './package';
// May contain unused imports in some cases
// @ts-ignore
import type { PartialShipment } from './partial-shipment';
// May contain unused imports in some cases
// @ts-ignore
import type { ShipmentItem } from './shipment-item';
// May contain unused imports in some cases
// @ts-ignore
import type { ShipmentStatus } from './shipment-status';
// May contain unused imports in some cases
// @ts-ignore
import type { ShippingAddress } from './shipping-address';
// May contain unused imports in some cases
// @ts-ignore
import type { ShippingAddressTo } from './shipping-address-to';
// May contain unused imports in some cases
// @ts-ignore
import type { Tag } from './tag';
// May contain unused imports in some cases
// @ts-ignore
import type { TaxIdentifier } from './tax-identifier';
// May contain unused imports in some cases
// @ts-ignore
import type { Weigth } from './weigth';

/**
 * @type Shipment
 * The information necessary to ship a package, such as the origin, the destination, the carrier service, and the package dimensions and weight.  > **Note:** Either `ship_from` or `warehouse_id` must be set. 
 * @export
 */
export type Shipment = PartialShipment;


