/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderSourceName } from './order-source-name';

/**
 * A shipment item
 * @export
 * @interface ShipmentItem
 */
export interface ShipmentItem {
    /**
     * item name
     * @type {string}
     * @memberof ShipmentItem
     */
    'name'?: string;
    /**
     * sales order id
     * @type {string}
     * @memberof ShipmentItem
     */
    'sales_order_id'?: string | null;
    /**
     * sales order item id
     * @type {string}
     * @memberof ShipmentItem
     */
    'sales_order_item_id'?: string | null;
    /**
     * The quantity of this item included in the shipment
     * @type {number}
     * @memberof ShipmentItem
     */
    'quantity'?: number;
    /**
     * Item Stock Keeping Unit
     * @type {string}
     * @memberof ShipmentItem
     */
    'sku'?: string | null;
    /**
     * external order id
     * @type {string}
     * @memberof ShipmentItem
     */
    'external_order_id'?: string | null;
    /**
     * external order item id
     * @type {string}
     * @memberof ShipmentItem
     */
    'external_order_item_id'?: string | null;
    /**
     * Amazon Standard Identification Number
     * @type {string}
     * @memberof ShipmentItem
     */
    'asin'?: string | null;
    /**
     * 
     * @type {OrderSourceName}
     * @memberof ShipmentItem
     */
    'order_source_code'?: OrderSourceName;
}



