/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AddressValidatingShipment } from './address-validating-shipment';

/**
 * 
 * @export
 * @interface ShipmentRequest
 */
export interface ShipmentRequest {
    /**
     * The shipment object
     * @type {AddressValidatingShipment}
     * @memberof ShipmentRequest
     */
    'shipment'?: AddressValidatingShipment;
}

