/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The possible shipments sort by values
 * @export
 * @enum {string}
 */

export const ShipmentsSortBy = {
    ModifiedAt: 'modified_at',
    CreatedAt: 'created_at'
} as const;

export type ShipmentsSortBy = typeof ShipmentsSortBy[keyof typeof ShipmentsSortBy];



