/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Tag } from './tag';

/**
 * A shipment add tag response body
 * @export
 * @interface TagShipmentResponseBody
 */
export interface TagShipmentResponseBody {
    /**
     * A string that uniquely identifies the shipment
     * @type {string}
     * @memberof TagShipmentResponseBody
     */
    'shipment_id': string;
    /**
     * The tag that is now associated with this shipment
     * @type {Tag}
     * @memberof TagShipmentResponseBody
     */
    'tag': Tag;
}

