/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IdentifierType } from './identifier-type';
// May contain unused imports in some cases
// @ts-ignore
import type { TaxableEntityType } from './taxable-entity-type';

/**
 * A tax identifier object
 * @export
 * @interface TaxIdentifier
 */
export interface TaxIdentifier {
    /**
     * 
     * @type {TaxableEntityType}
     * @memberof TaxIdentifier
     */
    'taxable_entity_type': TaxableEntityType;
    /**
     * 
     * @type {IdentifierType}
     * @memberof TaxIdentifier
     */
    'identifier_type': IdentifierType;
    /**
     * The authority that issued this tax. This must be a valid 2 character ISO 3166 Alpha 2 country code.
     * @type {string}
     * @memberof TaxIdentifier
     */
    'issuing_authority': string;
    /**
     * The value of the identifier
     * @type {string}
     * @memberof TaxIdentifier
     */
    'value': string;
}



