/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The taxable entity type for this tax item. Valid values include the following  |Value       |Description |:---------  |:----------------------------------------------------- |`shipper`   | The shipper is responsible for this tax. |`recipient` | The recipient of the shipment is responsible for this tax. |`ior`       | The importer of records is responsible for tax. 
 * @export
 * @enum {string}
 */

export const TaxableEntityType = {
    Shipper: 'shipper',
    Recipient: 'recipient',
    Ior: 'ior'
} as const;

export type TaxableEntityType = typeof TaxableEntityType[keyof typeof TaxableEntityType];



