/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TrackingStatusDetailCode } from './tracking-status-detail-code';

/**
 * A track event
 * @export
 * @interface TrackEvent
 */
export interface TrackEvent {
    /**
     * Timestamp for carrier event
     * @type {string}
     * @memberof TrackEvent
     */
    'occurred_at': string;
    /**
     * Carrier timestamp for the event, it is assumed to be the local time of where the event occurred.
     * @type {string}
     * @memberof TrackEvent
     */
    'carrier_occurred_at'?: string;
    /**
     * Event description
     * @type {string}
     * @memberof TrackEvent
     */
    'description'?: string;
    /**
     * City locality
     * @type {string}
     * @memberof TrackEvent
     */
    'city_locality': string;
    /**
     * State province
     * @type {string}
     * @memberof TrackEvent
     */
    'state_province': string;
    /**
     * Postal code
     * @type {string}
     * @memberof TrackEvent
     */
    'postal_code': string;
    /**
     * A two-letter [ISO 3166-1 country code](https://en.wikipedia.org/wiki/ISO_3166-1) 
     * @type {string}
     * @memberof TrackEvent
     */
    'country_code'?: string;
    /**
     * Company Name
     * @type {string}
     * @memberof TrackEvent
     */
    'company_name'?: string;
    /**
     * Signer information
     * @type {string}
     * @memberof TrackEvent
     */
    'signer'?: string;
    /**
     * Event Code
     * @type {string}
     * @memberof TrackEvent
     */
    'event_code'?: string;
    /**
     * Carrier detail code
     * @type {string}
     * @memberof TrackEvent
     */
    'carrier_detail_code': string;
    /**
     * 
     * @type {TrackingStatusDetailCode}
     * @memberof TrackEvent
     */
    'status_code': TrackingStatusDetailCode;
    /**
     * 
     * @type {TrackingStatusDetailCode}
     * @memberof TrackEvent
     */
    'status_detail_code'?: TrackingStatusDetailCode;
    /**
     * Event Status Description
     * @type {string}
     * @memberof TrackEvent
     */
    'status_description': string;
    /**
     * Event Status Detail Description
     * @type {string}
     * @memberof TrackEvent
     */
    'status_detail_description'?: string;
    /**
     * Carrier status code
     * @type {string}
     * @memberof TrackEvent
     */
    'carrier_status_code': string;
    /**
     * carrier status description
     * @type {string}
     * @memberof TrackEvent
     */
    'carrier_status_description': string;
    /**
     * Latitude coordinate of tracking event.
     * @type {number}
     * @memberof TrackEvent
     */
    'latitude'?: number;
    /**
     * Longitude coordinate of tracking event.
     * @type {number}
     * @memberof TrackEvent
     */
    'longitude'?: number;
}



