/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The different statuses that can apply to a shipment.
 * @export
 * @enum {string}
 */

export const TrackingStatus = {
    Unknown: 'unknown',
    InTransit: 'in_transit',
    Error: 'error',
    Delivered: 'delivered'
} as const;

export type TrackingStatus = typeof TrackingStatus[keyof typeof TrackingStatus];



