/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Used with the modify transaction type to update the cost of existing inventory
 * @export
 * @interface UpdateSKUStockLevelsRequestNewCost
 */
export interface UpdateSKUStockLevelsRequestNewCost {
    /**
     * 
     * @type {number}
     * @memberof UpdateSKUStockLevelsRequestNewCost
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateSKUStockLevelsRequestNewCost
     */
    'currency'?: string;
}

