/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The possible validation status values
 * @export
 * @enum {string}
 */

export const ValidationStatus = {
    Valid: 'valid',
    Invalid: 'invalid',
    HasWarnings: 'has_warnings',
    Unknown: 'unknown'
} as const;

export type ValidationStatus = typeof ValidationStatus[keyof typeof ValidationStatus];



