/* tslint:disable */
/* eslint-disable */
/**
 * ShipStation API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LabelVoidFailureReason } from './label-void-failure-reason';

/**
 * A void label response body
 * @export
 * @interface VoidLabelResponseBody
 */
export interface VoidLabelResponseBody {
    /**
     * Indicates whether the attempt to void the label was successful
     * @type {boolean}
     * @memberof VoidLabelResponseBody
     */
    'approved': boolean;
    /**
     * 
     * @type {string}
     * @memberof VoidLabelResponseBody
     */
    'message': string;
    /**
     * Indicates a normalized reason for the conditions if the void attempt was not approved. Will not populate if approved is true. “unknown” codes may be specified later.
     * @type {LabelVoidFailureReason}
     * @memberof VoidLabelResponseBody
     */
    'reason_code'?: LabelVoidFailureReason;
}



